server:
  port: 8080
spring:
    application:
        name: my-boot-zuul
eureka:
  instance:
    #eureka服务器的标识，如果是集群就可以写成 eurekaSer1,eurekaSer2,eurekaSer3..
    hostname: my-eureka
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
    max-total-connections: 200   #总连接数
    max-per-route-connections: 20  #每个路由连接数
  add-host-header: true

#  sensitive-headers:
logging:
  level:
    com.netflix: DEBUG
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
management:
  security:
    enabled: false

